kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    server {
      listen 8080;
      client_max_body_size 60M;

      access_log off;

      root /var/www/html;
      index index.php;

      server_tokens off;

      location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ /index.php?$args;
      }

      # pass the PHP scripts to FastCGI server listening on localhost:9000
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
      }

    }
  custom-php.ini: |-
    # Allow HTTP file uploads
    file_uploads = On

    # Maximum size of an uploaded file
    upload_max_filesize = 60M

    # Maximum size of form post data
    post_max_size = 60M
  www.conf: |-
    pm = dynamic
    pm.max_children = 25
    pm.start_servers = 10
    pm.min_spare_servers = 5
    pm.max_spare_servers = 20
    pm.max_requests = 498
