---
name: Deploy

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy App
        run: |
          echo "$KUBECONFIG_BASE64" | base64 -d
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
