---
name: Deploy

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master

env:
  IMAGE_NAME: wordpress/ly
  IMAGE_EMAIL: vibindaniel@outlook.com
  IMAGE_SECRET: ${{ secrets.IMAGE_SECRET }}
  IMAGE_REPOSITORY: ghcr.io

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_REPOSITORY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          outputs: type=image,name=${{ env.IMAGE_REPOSITORY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_REPOSITORY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL"

      - name: Run but not Fail Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_REPOSITORY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: "table"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REPOSITORY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy App
        shell: pwsh
        run: ./deploy.ps1
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
          IMAGE_USER: ${{ github.actor }}
          NAMESPACE: lynguyenministries
